power: power.o test-power.o
	gcc -o power power.o test-power.o
power.o: power.c
	gcc -Wall -Werror -pedantic -std=gnu99 -c power.c
test-power.o: test-power.c
	gcc -Wall -Werror -pedantic -std=gnu99 -c test-power.c
